services:
  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      # Remove HTTPS port for development
      # - "443:443"

  woothomes-frontend:
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev
    # Remove direct port mapping since Nginx handles it
    expose:
      - "3000" 